### PR TITLE
Export for use with package management

### PR DESCRIPTION
**Pull request by willemneal**
I'm able to get this to work with the new runtime, if you run `npx asp --notrace`. 
 However, `npx asp` results in rtrace finding that there are allocations that try to use the same block.

Also this adds a dependency for bignum, only to show that package management works.  Will remove it later.

### CODE REVIEW

**Comment by bowenwang1996** [comment]
I don't think we want to use `full` runtime now. It will break other things.

**Comment by willemneal** [comment]
Well it still works with stub.

**Comment by willemneal** [comment]
@bowenwang1996 @vgrichina 

This is needed for the new bindings code, which relies on the files now exported by `index.ts`.  If you don't want to also merge in my JSON Value stuff, I can pull it out and my another PR.

**Comment by bowenwang1996** [comment]
That sounds good. Let's not include the JSON value stuff in this PR

**Comment by willemneal** [comment]
@bowenwang1996  This is ready to merge.

**Comment by willemneal** [comment]
@bowenwang1996  @vgrichina I've been using my own repo for testing, but this needs to merge before we can ship.

**Comment by bowenwang1996** [comment]
Sure. We can merge this when everything is ready

**Comment by willemneal** [comment]
How about making a staging branch so that others being tested can depend on that?

**Comment by bowenwang1996** [comment]
Sure. I created a staging branch. Feel free to submit your PR there

**Pull request merged**
