### PR TITLE
Add CI Job to run "JSON Spec Test Suite" against as-json

### PR DESCRIPTION
**Pull request by ashutoshvarma**
# Assemblyscript-json - JSON Spec Test Suite

## Summary
This PR adds 
- a new CI job that runs [JSONSuiteTest](https://github.com/ashutoshvarma/JSONTestSuite) on every commit to master. 
- Also adds a new folder `utils` which contains helper wasm module `testsuite_helper` (to integrate with test suite) and bash script for Travis

## Rationale
[JSONSuiteTest](https://github.com/ashutoshvarma/JSONTestSuite) expects a executable binary which is passed a json file path as an argument, and on the basis of exit codes tests outcome is decided.
- `0` the parser did accept the content
- `1` the parser did reject the content
- `>1` the process did crash
- `timeout` happens after 5 seconds

Initially I tried to write a simple js cli script which will load and run `JSON.parse` from the compiled wasm for this but,

```js
❯ yarn asbuild
yarn run v1.22.5
$ yarn asbuild:untouched && yarn asbuild:optimized
$ asc assembly/index.ts -b build/untouched.wasm -t build/untouched.wat --sourceMap --validate --debug
...

WARNING AS232: Exported generic function or class has no concrete instances.

 export function parse<T = Uint8Array>(str: T): Value {
                 ~~~~~
 in assembly/JSON.ts(479,17)

...

Done in 7.64s.
```
Since `JSON.parse` is not exported to compiled wasm binary (build/ ), I decided to create a small CLI wasm (utils/testsuite_helper`).

### `utils/testsuite_helper`
This module exposes `JSON.parse` through a CLI environment for testing purposes.

### `utils/run_testsuite.sh`
Bash script to run the test suite.
- Clone the forked [JSONSuiteTest](https://github.com/ashutoshvarma/JSONTestSuite) repo.
- Build `testsuite_helper` and copy the newly built wasm module to testsuite parsers/.
- Run the test runner.

### CODE REVIEW

**Comment by ashutoshvarma** [comment]
Looks like the fossa CI job is working as expected, seems there is some issue with API keys

**Comment by ashutoshvarma** [comment]
Here is the output of new CI job
https://travis-ci.com/github/nearprotocol/assemblyscript-json/jobs/491902815

**Comment by willemneal** [comment]
Looks great so far!  You can ignore the Fossa errors for now.  Is there a way to generate the report as HTML?

**Comment by ashutoshvarma** [comment]
Actually, the test runner generates HTML results in /results dir, but Travis does not support storing CI artifacts.
So to access the generated HTML file we need to upload it somewhere, like S3 bucket.

Or, we can switch to Github Actions which cache artifacts for few weeks atleast.

**Comment by vgrichina** [comment]
@willemneal any reason not to merge?

**Review by willemneal — APPROVED** [review]

**Pull request merged**
