### PR TITLE
Added Prettier for code formatting

### PR DESCRIPTION
**Pull request by torch2424**
Hello! :smile: :wave: 

I added [prettier](https://prettier.io/) for code formatting on the project, because when I was going to implement parsing floats, I had realized the code wasn't formatted correctly. And I figured i'd add this first instead so things are more readable :smile: 

The only caveat being, I added a `.prettierignore` for `assembly/JSON.ts`, because I couldn't get it to take the `@global` and `@inline` annotations, but if you comment them out it works fine. So, I commented it, formatted, and the uncommented them for now. Perhaps in the future we can split this file out so that the actual implementation is formatted. But I think this should be fine.

I then ran the formatter on the project, and added a pre-commit hook to run the formatter on commit so the code stays formatted :smile: 

Let me know what you think! Thanks! :tada: 

Screenshot from 2021-01-14 11-58-29

### CODE REVIEW

**Comment by torch2424** [comment]
Oops, didn't realize you were using yarn. Should now be good to go :smile: :tada:

**Comment by willemneal** [comment]
I ditched prettier for assemblyscript in near-sdk-as and in as-pect.  Check out https://github.com/jtenner/as-pect/blob/master/.eslintrc.js

This is what as-pect uses and it doesn't complain about decorators.  Plus I adapted the rules from AssemblyScirpt's repo.  It also adds logic rules like removing unused imports, and unused variables.

Also when adding husky, I personally think it's best to check the formatting and fail with the fix so that you have a final step of adding the changes to be staged without it happening under the hood.  See an example here: https://github.com/near/near-sdk-as/blob/29b8ae5ab0598fba4a3353d7d465189eb0120de3/package.json#L39

**Comment by torch2424** [comment]
@willemneal Awesome! 

I'll go ahead and implement eslint, and the husky fixes :smile:  

Also it seems like the CI fails on node 10, because the newest AS version uses TextEncoder which wasn't in Node 10 I guess. So I'll also edit the travis file to drop that version? :smile:

**Comment by willemneal** [comment]
Yeah I think we can drop support for node v10.

Thanks for the help!

**Comment by torch2424** [comment]
@willemneal Addressed all your feedback! :smile: Added eslint, and husky that does the check for linting. 

And then I made the travis target node lts, and node stable per: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions

This is good to go! :smile:

**Review by willemneal — APPROVED** [review]

**Comment by torch2424** [comment]
Thanks for merging @willemneal ! :smile: :tada:

**Pull request merged**
